// ─── Mock Karyakarta Profiles ───────────────────────────────

import type { KaryakartaProfile } from '@/types/karyakarta.types';

const now = Date.now();
const d = (days: number) => new Date(now - days * 86400000).toISOString();

export const MOCK_PROFILES: KaryakartaProfile[] = [
  {
    $id: 'k1', $createdAt: d(30), $updatedAt: d(1),
    fullName: 'Rajesh Kumar Sharma', aliases: ['Raju Pandit', 'Sharma Ji'], fatherName: 'Late Mohan Sharma',
    dateOfBirth: '1978-03-15', ageEstimate: '47', gender: 'male',
    photoUrls: [],
    physicalDescription: { height: '5\'8"', build: 'medium', complexion: 'Fair', facialHair: 'mustache', distinguishingMarks: 'Scar on left forearm' },
    phoneNumbers: ['+91 98XXX XXXXX', '+91 87XXX XXXXX'], emails: ['r***@gmail.com'],
    socialMedia: [
      { platform: 'facebook', handle: 'rajesh.s***', followersCount: 2300, isVerified: false },
      { platform: 'twitter', handle: '@raju_p***', followersCount: 890 },
      { platform: 'whatsapp', handle: '+91 98XXX XXXXX' },
    ],
    addresses: [
      { type: 'current', address: 'H.No XX, Gali XX, Okhla Phase 2', area: 'Okhla Phase 2', city: 'New Delhi', pincode: '110020', since: '2019' },
      { type: 'shakha', address: 'Community Park, Block A', area: 'Okhla Phase 1' },
      { type: 'previous', address: 'Near Temple, Sector XX, Noida', city: 'Noida', until: '2019' },
    ],
    primaryArea: 'okhla_phase_2',
    frequentLocations: ['Okhla Industrial Area', 'Kalkaji Temple', 'Nehru Place Market'],
    rank: 'shakha_pramukh', affiliations: ['rss', 'vhp'],
    shakhaLocation: 'Community Park, Block A, Okhla Phase 1',
    shakhaTimings: '6:00 AM - 7:00 AM daily',
    seniorContact: 'Connected to Zila level',
    involvementSince: '2005', isActive: true,
    knownActivities: ['recruitment', 'training', 'ground_operations'],
    areasOfOperation: ['okhla_phase_1', 'okhla_phase_2', 'jasola'],
    linkedIncidentIds: ['1', '5'],
    sightings: [
      { date: d(2), location: 'Okhla Phase 1 Market', activity: 'recruitment', description: 'Seen distributing pamphlets at market entrance', isVerified: true },
      { date: d(7), location: 'Shaheen Bagh border', activity: 'surveillance', description: 'Photographing shops from a parked vehicle', isVerified: false },
    ],
    lastSeenDate: d(2), lastSeenLocation: 'Okhla Phase 1 Market',
    employmentHistory: [
      { occupation: 'Hardware Shop Owner', employer: 'Self-employed', address: 'Shop XX, Okhla Industrial Area', isCurrent: true, since: '2012' },
      { occupation: 'Electrician', employer: 'Various contractors', isCurrent: false, since: '2001', until: '2012' },
    ],
    vehicles: [{ type: 'motorcycle', number: 'DL XX XX XXXX', make: 'Honda Shine', color: 'Black' }],
    associates: [
      { profileId: 'k2', name: 'Suresh Yadav', relationship: 'peer', notes: 'Co-runs shakha' },
      { profileId: 'k4', name: 'Anand Tripathi', relationship: 'senior' },
    ],
    threatLevel: 'high', verificationStatus: 'partially_verified', reliabilityScore: 72,
    internalNotes: 'Key organizer in Okhla Phase 1-2 belt. Runs morning shakha consistently. Connected to district-level leadership.',
    sources: ['Field observation', 'Social media OSINT', 'Community report'],
    tags: ['organizer', 'shakha-runner', 'okhla-belt', 'active-recruiter'],
    createdBy: 'admin', updatedBy: 'mod1', isEncrypted: false,
  },
  {
    $id: 'k2', $createdAt: d(25), $updatedAt: d(3),
    fullName: 'Suresh Yadav', aliases: ['Suri'], gender: 'male',
    photoUrls: [], dateOfBirth: '1985-08-22', ageEstimate: '41',
    physicalDescription: { height: '5\'10"', build: 'heavy', facialHair: 'both', distinguishingMarks: 'Gold chain, ring on right hand' },
    phoneNumbers: ['+91 99XXX XXXXX'], emails: [],
    socialMedia: [
      { platform: 'facebook', handle: 'suresh.y***', followersCount: 1500 },
      { platform: 'whatsapp', handle: '+91 99XXX XXXXX' },
    ],
    addresses: [
      { type: 'current', address: 'Near Gurudwara, Jasola', area: 'Jasola', city: 'New Delhi' },
    ],
    primaryArea: 'jasola',
    frequentLocations: ['Jasola Market', 'Okhla Phase 1'],
    rank: 'karyavah', affiliations: ['rss', 'bjp'],
    isActive: true, involvementSince: '2010',
    knownActivities: ['fundraising', 'logistics', 'ground_operations'],
    areasOfOperation: ['jasola', 'okhla_phase_1'],
    linkedIncidentIds: ['6'], sightings: [],
    lastSeenDate: d(5), lastSeenLocation: 'Jasola Market',
    employmentHistory: [{ occupation: 'Auto Parts Dealer', employer: 'Self-employed', isCurrent: true, since: '2008' }],
    vehicles: [{ type: 'car', number: 'DL XX XX XXXX', make: 'Maruti Ertiga', color: 'White' }],
    associates: [{ profileId: 'k1', name: 'Rajesh Kumar Sharma', relationship: 'peer' }],
    threatLevel: 'medium', verificationStatus: 'partially_verified', reliabilityScore: 65,
    internalNotes: 'Handles logistics and funding for local shakhas. Owns an auto parts shop used as meeting point.',
    sources: ['Community report', 'Market observation'], tags: ['logistics', 'funding', 'jasola'],
    createdBy: 'admin', updatedBy: 'admin', isEncrypted: false,
  },
  {
    $id: 'k3', $createdAt: d(20), $updatedAt: d(0),
    fullName: 'Priya Verma', aliases: [], gender: 'female',
    photoUrls: [], ageEstimate: '28-32',
    physicalDescription: { height: '5\'4"', build: 'slim' },
    phoneNumbers: ['+91 70XXX XXXXX'], emails: ['p***@outlook.com'],
    socialMedia: [
      { platform: 'instagram', handle: '@priya_v***', followersCount: 4200, isVerified: false },
      { platform: 'twitter', handle: '@priyav***', followersCount: 3100 },
      { platform: 'facebook', handle: 'priya.verma***', followersCount: 1800 },
      { platform: 'telegram', handle: '@bharat_s***' },
    ],
    addresses: [
      { type: 'current', address: 'Somewhere in Kalkaji area', city: 'New Delhi' },
    ],
    primaryArea: 'okhla_phase_2',
    frequentLocations: ['Nehru Place', 'Kalkaji', 'Okhla Phase 2'],
    rank: 'unknown', affiliations: ['bjp_it_cell', 'abvp'],
    isActive: true, involvementSince: '2018',
    knownActivities: ['social_media', 'propaganda', 'recruitment'],
    areasOfOperation: ['okhla_phase_2', 'jamia_nagar'],
    linkedIncidentIds: ['4', '11'], sightings: [
      { date: d(1), location: 'Online — Twitter/X', activity: 'social_media', description: 'Coordinated hashtag campaign targeting minority institutions', isVerified: true },
    ],
    lastSeenDate: d(1), lastSeenLocation: 'Online',
    employmentHistory: [{ occupation: 'Freelance Social Media Manager', isCurrent: true, since: '2020' }],
    vehicles: [], associates: [],
    threatLevel: 'medium', verificationStatus: 'unverified', reliabilityScore: 48,
    internalNotes: 'Primarily online operator. Runs multiple WhatsApp/Telegram groups for coordination. Suspected ABVP background from JNU days.',
    sources: ['Social media OSINT'], tags: ['it-cell', 'online-operator', 'social-media', 'propaganda'],
    createdBy: 'mod1', updatedBy: 'mod1', isEncrypted: false,
  },
  {
    $id: 'k4', $createdAt: d(15), $updatedAt: d(2),
    fullName: 'Anand Tripathi', aliases: ['Pandit Ji', 'Anand Bhai'], gender: 'male',
    photoUrls: [], dateOfBirth: '1965-01-10', ageEstimate: '61',
    physicalDescription: { height: '5\'6"', build: 'medium', facialHair: 'none', complexion: 'Wheatish', distinguishingMarks: 'Wears white kurta-pajama daily, tilak on forehead' },
    phoneNumbers: ['+91 98XXX XXXXX', '+91 81XXX XXXXX'], emails: [],
    socialMedia: [{ platform: 'whatsapp', handle: '+91 98XXX XXXXX' }],
    addresses: [
      { type: 'current', address: 'Near Kali Mandir, Batla House', area: 'Batla House', city: 'New Delhi' },
      { type: 'shakha', address: 'Open ground near Jogabai Extension', area: 'Johri Farm' },
    ],
    primaryArea: 'batla_house',
    frequentLocations: ['Batla House', 'Johri Farm', 'Jamia Nagar'],
    rank: 'pracharak', affiliations: ['rss', 'vhp', 'hindu_jagran_manch'],
    shakhaLocation: 'Open ground near Jogabai Extension',
    shakhaTimings: '5:30 AM - 6:30 AM',
    seniorContact: 'State-level pracharak network',
    involvementSince: '1988', isActive: true,
    knownActivities: ['leadership', 'recruitment', 'training', 'intimidation'],
    areasOfOperation: ['batla_house', 'jamia_nagar', 'johri_farm', 'zakir_nagar'],
    linkedIncidentIds: ['2', '7', '10'], sightings: [
      { date: d(4), location: 'Johri Farm market', activity: 'intimidation', description: 'Pressured shopkeepers to display specific flags', isVerified: true },
      { date: d(10), location: 'Batla House community hall', activity: 'leadership', description: 'Conducted meeting with 30+ attendees', isVerified: true },
    ],
    lastSeenDate: d(4), lastSeenLocation: 'Johri Farm Market',
    employmentHistory: [{ occupation: 'Full-time Pracharak', notes: 'No known external employment', isCurrent: true, since: '1995' }],
    vehicles: [{ type: 'scooter', make: 'Honda Activa', color: 'Grey' }],
    associates: [
      { profileId: 'k1', name: 'Rajesh Kumar Sharma', relationship: 'junior' },
      { profileId: 'k5', name: 'Vikram Singh', relationship: 'peer' },
    ],
    threatLevel: 'critical', verificationStatus: 'verified', reliabilityScore: 91,
    internalNotes: 'Senior-most RSS pracharak identified in Okhla-Jamia belt. Full-time worker since 1995. Directly linked to state-level command chain. Key figure in Batla House/Johri Farm area operations.',
    sources: ['Long-term field observation', 'Multiple community reports', 'Incident correlation'],
    tags: ['pracharak', 'senior-leadership', 'batla-house', 'high-priority', 'verified'],
    createdBy: 'admin', updatedBy: 'admin', isEncrypted: false,
  },
  {
    $id: 'k5', $createdAt: d(10), $updatedAt: d(5),
    fullName: 'Vikram Singh', aliases: ['Vicky'], gender: 'male',
    photoUrls: [], ageEstimate: '30-35',
    physicalDescription: { height: '5\'11"', build: 'muscular', facialHair: 'beard', distinguishingMarks: 'Tattoo on right arm, usually wears saffron wristband' },
    phoneNumbers: ['+91 88XXX XXXXX'], emails: [],
    socialMedia: [
      { platform: 'instagram', handle: '@vikram_s***', followersCount: 950 },
      { platform: 'facebook', handle: 'vikram.singh***' },
    ],
    addresses: [{ type: 'current', address: 'Shaheen Bagh area', area: 'Shaheen Bagh', city: 'New Delhi' }],
    primaryArea: 'shaheen_bagh',
    frequentLocations: ['Shaheen Bagh', 'Abul Fazal Enclave border', 'Kalindi Kunj'],
    rank: 'shakha_pramukh', affiliations: ['rss', 'bajrang_dal'],
    isActive: true, involvementSince: '2015',
    knownActivities: ['training', 'surveillance', 'intimidation', 'ground_operations'],
    areasOfOperation: ['shaheen_bagh', 'abul_fazal_enclave'],
    linkedIncidentIds: ['1', '3', '9'], sightings: [
      { date: d(1), location: 'Shaheen Bagh market', activity: 'surveillance', description: 'Observed taking photographs of residential buildings', isVerified: false },
    ],
    lastSeenDate: d(1), lastSeenLocation: 'Shaheen Bagh Market',
    employmentHistory: [{ occupation: 'Gym Trainer', employer: 'Local gym', isCurrent: true, since: '2018' }],
    vehicles: [{ type: 'motorcycle', make: 'Royal Enfield', color: 'Black', number: 'DL XX XX XXXX' }],
    associates: [{ profileId: 'k4', name: 'Anand Tripathi', relationship: 'senior' }],
    threatLevel: 'high', verificationStatus: 'partially_verified', reliabilityScore: 68,
    internalNotes: 'Physical training specialist. Conducts drills and manages youth cadre in Shaheen Bagh border zone. Bajrang Dal connections.',
    sources: ['Field observation', 'Social media'], tags: ['shaheen-bagh', 'physical-training', 'bajrang-dal', 'surveillance'],
    createdBy: 'mod1', updatedBy: 'mod1', isEncrypted: false,
  },
];
